#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    current_time=$(date +%H:%M:%S)
    echo "$current_time: dockerid not available"
    exit 1  # Exit with a non-zero status to indicate an error
fi

sudo docker stop "$1"
