#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    current_time=$(date +%H:%M:%S)
    echo "$current_time: Usage: $0 <docker_id>"
    exit 1  # Exit with a non-zero status to indicate an error
fi

sudo docker stop "$1"
